services:
  # Backend
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/AKW254/Chillazi-Agent
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile

    envVars:
      - fromGroup: backend-env-group

  # Frontend
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/AKW254/Chillazi-Agent
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile

    envVars:
      - key: VITE_API_URL
        value: https://backend-ycne.onrender.com
